language: ruby
rvm: 2.3.1
sudo: false

addons:
    apt:
      packages:
        - vim-gtk

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - vim --version
  - cp example.vimrc ~/.vimrc
  - vim +PlugInstall +qall
  - curl https://releases.hashicorp.com/terraform/0.9.4/terraform_0.9.4_linux_amd64.zip -o terraform_0.9.4_linux_amd64.zip
  - unzip terraform_0.9.4_linux_amd64.zip
  - mv terraform /usr/bin/terraform
  - vim +PlugInstall

script:
  - vim +Vader! tests/* && echo Success || echo Failure
